### PR TITLE
Fix compatibility with twig 3.9 and yielding

### LINKED ISSUE #343: Incompatibility with twig 3.9
Since https://github.com/twigphp/Twig/pull/3999 we cannot use `ob_` method to get the generated output.
As a result, the the [output generated](https://github.com/nelmio/NelmioSecurityBundle/blob/6a6c75ef6342385ef732f0b5afa705660177250f/src/Twig/Node/CSPNode.php#L42-L59) by the CSPNode is empty.
Which lead to an exception `Invalid script, you should use a single <script> tag.`

My template twig is:
```
            {% cspscript %}
                <script>
                  alert('foo')
                </script>
            {% endcspscript %}
```

the generated PHP code is

```

        // line 315
        yield "            ";
        ob_start();
        yield "                <script>
                  alert('foo')
                </script>
            ";
        $this->env->getRuntime('Nelmio\SecurityBundle\Twig\CSPRuntime')->getListener()->addSha('script-src', 'sha384-Ee2u6OPPCwK16NVPQ56ORx7yfwYmCmO+bYzRi4OsT+wo/iiP9f8p/+7GNTdT2++t');
echo ob_get_clean();
        // line 320
        yield "        ";
```

The content of `ob_get_clean();` is `""`.

### PR DESCRIPTION
**Pull request by jderusse**
This PR makes CSPNode compatible with twig 3.9.

Since https://github.com/twigphp/Twig/pull/3999 we cannot use `ob_` method to get the generated output (See https://github.com/twigphp/Twig/issues/4034)

This PR fixes the issue by using the CaptureNode introduced in https://github.com/twigphp/Twig/pull/3954

Fix #343

### CODE REVIEW

File: src/Twig/Node/CSPNode.php [hunk 1]
```diff
@@ -22,40 +22,60 @@
...
+                ->outdent()
+            ;
+        } else {
+            $compiler
+                ->addDebugInfo($this)
+                ->indent()
+                ->write("ob_start();\n")
+                ->subcompile($this->getNode('body'))
+                ->outdent()
+                ->write("\$output = ob_get_clean();\n")
```
[the remark this answers is not in the document]
Comment (jderusse) [reply src/Twig/Node/CSPNode.php]: of course :facepalm:

**Comment by parijke** [comment]
When are we going to merge this one? My business depends on it, so this would be very nice.

**Review by franmomu — APPROVED** [review]

**Comment by franmomu** [comment]
thanks @jderusse!

File: src/Twig/Node/CSPNode.php [hunk 2]
```diff
@@ -22,40 +22,60 @@
...
             throw new \InvalidArgumentException(sprintf('Unable to compile for directive "%s"', $this->directive));
         }
-
-        $compiler
-            ->addDebugInfo($this)
-            ->write("ob_start();\n")
-            ->subcompile($body)
-            ->write($output)
-        ;
+        $compiler->write("echo \$content;\n");
```
Comment (Seldaek) [inline src/Twig/Node/CSPNode.php:79]: I still get deprecation warnings in the test suite which I think are coming from this line?

  4x: Since twig/twig 3.9: Using "echo" is deprecated, use "yield" instead in "Nelmio\SecurityBundle\Twig\Node\CSPNode", then flag the class with #[YieldReady].
    2x in IntegrationTest::testItWorksDynamically from Nelmio\SecurityBundle\Tests\Twig
    2x in IntegrationTest::testItWorksStatically from Nelmio\SecurityBundle\Tests\Twig

Should this not be a yield?

Comment (jderusse) [reply src/Twig/Node/CSPNode.php:79]: indeed :(
